"""
Interpolation analysis for GCU predictor
- Reproduces the JS `interp()` behavior (baseline)
- Implements two smoothing strategies:
  - densify: insert synthetic runners between existing profiles
  - weighted: weighted k-NN / inverse-distance weighting across profiles
- Runs scenario tests (user-reported cases) and prints results

Run: python analysis/interp_analysis.py
"""

from math import fabs, exp
from statistics import median

# Reference profiles (cumulative minutes at checkpoints):
# [Start, Swiman, Castleburn, Mzimkulwana, Cobham, Finish]
DEFAULT_PR = [
    [0, 73, 139, 212, 266, 362],
    [0, 85, 164, 248, 311, 429],
    [0, 92, 179, 280, 357, 490],
    [0,105, 196, 301, 379, 524],
    [0,111, 213, 322, 401, 542],
    [0,123, 223, 332, 419, 577],
    [0,125, 231, 358, 449, 615],
    [0,126, 252, 391, 492, 669],
    [0,133, 267, 420, 538, 740],
    [0,138, 287, 471, 585, 796],
    [0,175, 335, 505, 660, 870],
]

import os, json

# If an expanded PR file exists (generated by analysis/fetch_sportraxs.py),
# load and use it; otherwise fall back to DEFAULT_PR
PR = DEFAULT_PR
try:
    path = os.path.join(os.path.dirname(__file__), 'expanded_pr.json')
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8') as fh:
            loaded = json.load(fh)
            if isinstance(loaded, list) and len(loaded) > 0:
                PR = loaded
                print(f'Loaded expanded PR with {len(PR)} profiles from {path}')
except Exception:
    # ignore and use DEFAULT_PR
    PR = DEFAULT_PR

CP_NAMES = ["Start", "Swiman", "Castleburn", "Mzimkulwana", "Cobham", "Finish"]
NUM_CP = len(CP_NAMES)

# --- Baseline JS interp() recreation ---

def interp_js(ci, el, PR_list=PR):
    """Replicate the JS interp(ci,el) function: linear interpolation
    between the two reference profiles that bracket `el` at checkpoint ci.
    Returns a list of predicted cumulative minutes at each checkpoint.
    """
    n = len(PR_list)
    lo, hi = 0, 1
    if el <= PR_list[0][ci]:
        lo, hi = 0, 1
    elif el >= PR_list[n - 1][ci]:
        lo, hi = n - 2, n - 1
    else:
        for i in range(n - 1):
            if PR_list[i][ci] <= el <= PR_list[i + 1][ci]:
                lo, hi = i, i + 1
                break
    rng = PR_list[hi][ci] - PR_list[lo][ci]
    a = (el - PR_list[lo][ci]) / rng if rng > 0 else 0.0
    return [PR_list[lo][f] + a * (PR_list[hi][f] - PR_list[lo][f]) for f in range(NUM_CP)]

# --- Weighted interpolation (k-NN / inverse distance) ---

def interp_weighted(ci, el, PR_list=PR, k=None, p=2, eps=1e-6):
    """Compute a weighted interpolation across reference profiles.
    Weights are inverse-distance^p (with small eps). If k is provided,
    use the k nearest profiles by distance; otherwise use all.
    Returns a predicted profile list.
    """
    # distances
    dist_idx = [(abs(pr[ci] - el), idx) for idx, pr in enumerate(PR_list)]
    dist_idx.sort()

    # If exact match, return that profile immediately
    if dist_idx and dist_idx[0][0] == 0:
        return PR_list[dist_idx[0][1]].copy()

    # If k provided, use k-nearest inverse-distance weighting (legacy behavior)
    if k is not None:
        chosen = dist_idx[:k]
        weights = []
        for d, idx in chosen:
            w = 1.0 / ((d + eps) ** p)
            weights.append((w, idx))
        W = sum(w for w, _ in weights)
        if W == 0:
            return interp_js(ci, el, PR_list)
        res = []
        for f in range(NUM_CP):
            val = sum(PR_list[idx][f] * w for w, idx in weights) / W
            res.append(val)
        return res

    # Adaptive / bandwidth-based weighting when k is None
    # Use a Gaussian-like kernel combined with inverse-distance to downweight far profiles.
    dlist = [d for d, _ in dist_idx]
    nonzero = [d for d in dlist if d > eps]
    if nonzero:
        h = max(median(nonzero), 1.0)
    else:
        h = 1.0

    weights = []
    for d, idx in dist_idx:
        # gaussian kernel times inverse-distance^p
        gw = exp(-0.5 * (d / h) ** 2)
        w = gw / ((d + eps) ** p)
        weights.append((w, idx))
    W = sum(w for w, _ in weights)
    if W == 0:
        return interp_js(ci, el, PR_list)
    res = []
    for f in range(NUM_CP):
        val = sum(PR_list[idx][f] * w for w, idx in weights) / W
        res.append(val)
    return res

# --- Densify / synthetic runners insertion ---

def densify_pr(PR_list=PR, factor=3):
    """Return a new PR list with synthetic profiles inserted between
    each adjacent pair. `factor` = how many total samples per original
    interval (>=2). E.g. factor=3 inserts 2 equally spaced points.
    """
    assert factor >= 2
    new = []
    n = len(PR_list)
    for i in range(n - 1):
        a = PR_list[i]
        b = PR_list[i + 1]
        new.append(a.copy())
        for step in range(1, factor):
            alpha = step / float(factor)
            synth = [a[f] + alpha * (b[f] - a[f]) for f in range(NUM_CP)]
            new.append(synth)
    new.append(PR_list[-1].copy())
    return new

# --- Fade calculation (replicate JS calcFade) ---

def calc_fade_from_entries(entries, interp_fn):
    """entries: list of dicts [{'cp':idx,'min':minutes}, ...]
    interp_fn: function(ci, el) -> profile list
    Returns fade value (min/hr) computed like the JS code.
    """
    if len(entries) < 2:
        return 0.0
    preds = []
    for e in entries:
        profile = interp_fn(e['cp'], e['min'])
        preds.append({'el': e['min'], 'fin': profile[-1]})
    f = preds[0]
    l = preds[-1]
    hrs = (l['el'] - f['el']) / 60.0
    if hrs <= 0:
        return 0.0
    return ((l['fin'] - f['fin']) / hrs) * 0.5


def enforce_monotonic_profiles(profiles, eps=1e-6):
    """Ensure profile final times are non-decreasing in-order by adjusting
    any profile whose finish is earlier than the previous profile's finish.
    Adjustment scales the profile between its base (usually 0) and finish
    so the shape is preserved while enforcing monotonic finish times.
    Modifies the list in-place and also returns it.
    """
    prev_fin = None
    for i, pr in enumerate(profiles):
        fin = pr[-1]
        base = pr[0] if len(pr) > 0 else 0.0
        if prev_fin is None:
            prev_fin = fin
            continue
        if fin < prev_fin - eps:
            new_fin = prev_fin
            denom = pr[-1] - base
            if denom <= eps:
                # degenerate: set finish and leave other points spaced towards finish
                profiles[i] = [base + (new_fin - base) * (j / float(NUM_CP - 1)) for j in range(NUM_CP)]
            else:
                r = (new_fin - base) / denom
                profiles[i] = [base + r * (x - base) for x in pr]
            fin = new_fin
        prev_fin = fin
    return profiles


def predict_profiles_for_entries(entries, method_fn, enforce_mono=False):
    """Compute predicted profiles for each entry using method_fn.
    If enforce_mono is True, ensure non-decreasing final times across entries.
    Returns list of profile lists in the same order as entries.
    """
    profiles = [method_fn(e['cp'], e['min']) for e in entries]
    if enforce_mono and len(profiles) > 1:
        enforce_monotonic_profiles(profiles)
    return profiles


def compute_fade_from_profiles(entries, profiles):
    """Compute fade given original entries and their corresponding predicted profiles."""
    if len(entries) < 2:
        return 0.0
    f = profiles[0]
    l = profiles[-1]
    hrs = (entries[-1]['min'] - entries[0]['min']) / 60.0
    if hrs <= 0:
        return 0.0
    return ((l[-1] - f[-1]) / hrs) * 0.5


def compute_fade_for_entries(entries, method_fn, enforce_mono=False):
    """Convenience wrapper: predict profiles then compute fade."""
    profiles = predict_profiles_for_entries(entries, method_fn, enforce_mono=enforce_mono)
    return compute_fade_from_profiles(entries, profiles)


def bulk_test(sw_range, cb_range, methods):
    """Run a grid of Swiman x Castleburn times and count negative fades.
    Prints a concise summary of how often each method produces negative fade
    and how monotonic enforcement changes that count.
    """
    total = 0
    stats = {name: {'neg_raw': 0, 'neg_mono': 0} for name, _ in methods}
    for sw in sw_range:
        for cb in cb_range:
            if cb <= sw:
                continue
            total += 1
            entries = [{'cp': 1, 'min': sw}, {'cp': 2, 'min': cb}]
            for name, fn in methods:
                fade_raw = compute_fade_for_entries(entries, fn, enforce_mono=False)
                fade_mono = compute_fade_for_entries(entries, fn, enforce_mono=True)
                if fade_raw < 0:
                    stats[name]['neg_raw'] += 1
                if fade_mono < 0:
                    stats[name]['neg_mono'] += 1

    print(f"\nBulk test over {total} scenarios:")
    for name in stats:
        print(f"  {name:12} : negative fades raw={stats[name]['neg_raw']:4d}, with_mono={stats[name]['neg_mono']:4d}")


def extended_bulk_test(sw_range, cb_range, mz_range, methods, max_outliers=10):
    """Extended test: grid of Swiman x Castleburn x Mzimkulwana.
    For each combination (cb > sw, mz > cb), compute fades and look for outliers.
    Outliers: fade < -10, fade > 15, or sudden changes.
    Also check monotonicity in predicted profiles.
    """
    outliers = []
    total = 0
    for sw in sw_range:
        for cb in cb_range:
            if cb <= sw:
                continue
            for mz in mz_range:
                if mz <= cb:
                    continue
                total += 1
                entries = [{'cp': 1, 'min': sw}, {'cp': 2, 'min': cb}, {'cp': 3, 'min': mz}]
                for name, fn in methods:
                    # Compute profiles with and without monotonic enforcement
                    profs_raw = predict_profiles_for_entries(entries, fn, enforce_mono=False)
                    profs_mono = predict_profiles_for_entries(entries, fn, enforce_mono=True)
                    
                    # Fades: sw->cb, cb->mz, sw->mz
                    fade_sw_cb_raw = compute_fade_from_profiles(entries[:2], profs_raw[:2])
                    fade_cb_mz_raw = compute_fade_from_profiles(entries[1:3], profs_raw[1:3])
                    fade_sw_mz_raw = compute_fade_from_profiles(entries, profs_raw)
                    
                    fade_sw_cb_mono = compute_fade_from_profiles(entries[:2], profs_mono[:2])
                    fade_cb_mz_mono = compute_fade_from_profiles(entries[1:3], profs_mono[1:3])
                    fade_sw_mz_mono = compute_fade_from_profiles(entries, profs_mono)
                    
                    # Check for outliers
                    if (fade_sw_cb_raw < -10 or fade_cb_mz_raw < -10 or fade_sw_mz_raw < -10 or
                        fade_sw_cb_raw > 15 or fade_cb_mz_raw > 15 or fade_sw_mz_raw > 15 or
                        abs(fade_cb_mz_raw - fade_sw_cb_raw) > 10):  # sudden change
                        outliers.append({
                            'method': name,
                            'sw': sw, 'cb': cb, 'mz': mz,
                            'fade_sw_cb_raw': fade_sw_cb_raw, 'fade_cb_mz_raw': fade_cb_mz_raw, 'fade_sw_mz_raw': fade_sw_mz_raw,
                            'fade_sw_cb_mono': fade_sw_cb_mono, 'fade_cb_mz_mono': fade_cb_mz_mono, 'fade_sw_mz_mono': fade_sw_mz_mono,
                            'fin_raw': profs_raw[-1][-1], 'fin_mono': profs_mono[-1][-1]
                        })
                    
                    # Also check if raw profile finishes are not monotonic
                    raw_finishes = [p[-1] for p in profs_raw]
                    if any(raw_finishes[i] < raw_finishes[i-1] for i in range(1, len(raw_finishes))):
                        outliers.append({
                            'method': name, 'type': 'non-monotonic raw',
                            'sw': sw, 'cb': cb, 'mz': mz,
                            'finishes': raw_finishes
                        })

    # Sort outliers by severity (e.g., most negative fade)
    outliers.sort(key=lambda x: min(x.get('fade_sw_cb_raw', 0), x.get('fade_cb_mz_raw', 0), x.get('fade_sw_mz_raw', 0)))
    print(f"\nExtended bulk test over {total} scenarios. Top {max_outliers} outliers:")
    for i, out in enumerate(outliers[:max_outliers]):
        if 'type' in out:
            print(f"  {i+1}. {out['method']} ({out['type']}): sw={out['sw']}, cb={out['cb']}, mz={out['mz']}, finishes={out['finishes']}")
        else:
            print(f"  {i+1}. {out['method']}: sw={out['sw']}, cb={out['cb']}, mz={out['mz']}, fades_raw=({out['fade_sw_cb_raw']:+.1f}, {out['fade_cb_mz_raw']:+.1f}, {out['fade_sw_mz_raw']:+.1f}), fades_mono=({out['fade_sw_cb_mono']:+.1f}, {out['fade_cb_mz_mono']:+.1f}, {out['fade_sw_mz_mono']:+.1f}), fin_raw={out['fin_raw']:.1f}, fin_mono={out['fin_mono']:.1f}")


# --- Utility to show results for a scenario ---

def scenario_test(entries, test_mz_values=None):
    """entries: list of dicts (user-entered) sorted by cp
    test_mz_values: list of minutes to test for Mzimkulwana as "manual" last input
    Runs baseline + weighted + densified methods and prints comparisons.
    """
    print("\n--- Scenario: entries = {} ---".format(entries))
    # baseline predictions for each entry
    js_preds = [interp_js(e['cp'], e['min']) for e in entries]
    print("Baseline (JS) predicted finishes for entries:")
    for e, p in zip(entries, js_preds):
        print(f"  cp {e['cp']} ({CP_NAMES[e['cp']]} {e['min']} min) -> finish {p[-1]:.1f} min")

    # If there are exactly two entries and the second is Castleburn (cp=2),
    # compute predicted Mzimkulwana from baseline and other methods
    if len(entries) >= 2:
        first = entries[0]
        last = entries[-1]
        print('\nComparing methods for predicted finish at Castleburn and for varying Mzim times:')
        methods = [
            ('js', interp_js),
            ('weighted_k3', lambda ci, el: interp_weighted(ci, el, PR_list=PR, k=3, p=2)),
            ('weighted_k5', lambda ci, el: interp_weighted(ci, el, PR_list=PR, k=5, p=2)),
            ('densify_x3', lambda ci, el: interp_js(ci, el, PR_list=densify_pr(PR, factor=3))),
            ('densify_x5', lambda ci, el: interp_js(ci, el, PR_list=densify_pr(PR, factor=5))),
        ]

        # Pred finish from last entry for each method (raw vs monotonic-adjusted)
        print('\nPredicted finish (from last entered split) by method:')
        for name, fn in methods:
            profs_raw = predict_profiles_for_entries(entries, fn, enforce_mono=False)
            profs_mono = predict_profiles_for_entries(entries, fn, enforce_mono=True)
            pf_raw = profs_raw[-1][-1]
            pf_mono = profs_mono[-1][-1]
            print(f"  {name:12}: raw {pf_raw:.1f} min, mono {pf_mono:.1f} min")

        # If user provided test_mz_values, compute fade between last (Castleburn) interp and manual Mzim input
        if test_mz_values:
            print('\nFade values for varying Mzimkulwana inputs (compared to Castleburn entry):')
            for mz in test_mz_values:
                    print(f"\nMzimkulwana = {mz} min:")
                    for name, fn in methods:
                        # raw finishes (computed independently)
                        fin_cb_raw = fn(last['cp'], last['min'])[-1]
                        fin_mz_raw = fn(3, mz)[-1]
                        hrs = (mz - last['min']) / 60.0
                        fade_raw = ((fin_mz_raw - fin_cb_raw) / hrs) * 0.5 if hrs > 0 else 0.0

                        # monotonic enforcement across the pair [Castleburn, Mzim]
                        pair_entries = [last, {'cp': 3, 'min': mz}]
                        pair_profiles_mono = predict_profiles_for_entries(pair_entries, fn, enforce_mono=True)
                        fade_mono = compute_fade_from_profiles(pair_entries, pair_profiles_mono)

                        tag_raw = 'NEG' if fade_raw < 0 else 'POS'
                        tag_mono = 'NEG' if fade_mono < 0 else 'POS'
                        print(f"  {name:12} raw_fin_cb={fin_cb_raw:.1f} raw_fin_mz={fin_mz_raw:.1f} raw_fade={fade_raw:+6.1f} ({tag_raw})")
                        print(f"  {name:12} mono_fin_cb={pair_profiles_mono[0][-1]:.1f} mono_fin_mz={pair_profiles_mono[1][-1]:.1f} mono_fade={fade_mono:+6.1f} ({tag_mono})")

# --- Run tests for the user-reported scenario ---

def main():
    # User reported case: Swiman 2:10 (130), Castleburn 3:55 (235)
    entries = [ {'cp':1, 'min':130}, {'cp':2, 'min':235} ]
    # the user reported predicted Mzim ~316 (5:16). We'll test a range where they observed odd feedback
    mz_tests = [316, 330, 350, 380, 390, 402]  # 316=5:16, 402=6:42 which they mentioned
    scenario_test(entries, test_mz_values=mz_tests)

    # Also test the exact case the user had earlier: Swiman 125-126 vs Castleburn 235 to see sensitivity
    print('\n\n-- Sensitivity around Swiman 125/126 with Castleburn 235 --')
    for sw in [124, 125, 126, 127]:
        entries = [ {'cp':1, 'min':sw}, {'cp':2, 'min':235} ]
        print(f"\nSwiman={sw} min: ")
        scenario_test(entries, test_mz_values=[330])

    # Bulk grid test to quantify negative-fade frequency across many inputs
    methods = [
        ('js', interp_js),
        ('weighted_k3', lambda ci, el: interp_weighted(ci, el, PR_list=PR, k=3, p=2)),
        ('weighted_k5', lambda ci, el: interp_weighted(ci, el, PR_list=PR, k=5, p=2)),
        ('weighted_adaptive', lambda ci, el: interp_weighted(ci, el, PR_list=PR, k=None, p=2)),
        ('densify_x3', lambda ci, el: interp_js(ci, el, PR_list=densify_pr(PR, factor=3))),
    ]
    sw_range = range(100, 141, 5)   # Swiman times
    cb_range = range(200, 261, 5)   # Castleburn times
    mz_range = range(300, 451, 25)  # Mzimkulwana times: 300,325,350,375,400,425,450
    extended_bulk_test(sw_range, cb_range, mz_range, methods)

if __name__ == '__main__':
    main()
